version: '3'
services:
  discovery-service:
    build: 
      context: ./service-discovery
    image: discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - psiboard-network

  gateway-service:
    build: 
      context: ./api-gateway
    image: gateway-service
    container_name: gateway-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - psiboard-network
    depends_on:
      - discovery-service

  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: psiboard-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - psiboard-network
  
  redis:
    image: redis
    container_name: psiboard-redis
    ports:
      - 6379:6379
    networks:
      - psiboard-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - prometheus_data:/etc/prometheus
      - ./.monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - psiboard-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3001:3000
    restart: unless-stopped
    volumes:
      - grafana_data:/etc/grafana
      - ./.monitoring/grafana/datasources.yml:/etc/grafana/datasources.yml
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Usuário/senha padrão
    networks:
      - psiboard-network
    depends_on:
      - prometheus


  users-service:
    build: 
      context: ./users-service
    image: users-service
    container_name: users-service
    environment:
      - JWT_SECRET=my-secret-key
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - DATABASE_URL=jdbc:postgresql://${PGHOST}/${PGDATABASE}?user=${PGUSER}&password=${PGPASSWORD}&sslmode=require
      - DATABASE_USER=${PGUSER}
      - DATABASE_PASSWORD=${PGPASSWORD}
    ports:
      - "8081:8081"
    networks:
      - psiboard-network
    depends_on:
      - discovery-service

  patients-service:
    build: 
      context: ./patients-service
    image: patients-service
    container_name: patients-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - DATABASE_URL=jdbc:postgresql://${PGHOST}/${PGDATABASE}?user=${PGUSER}&password=${PGPASSWORD}&sslmode=require
      - DATABASE_USER=${PGUSER}
      - DATABASE_PASSWORD=${PGPASSWORD}
      - RABBITMQ_ADDRESS=${RABBITMQ_ADDRESS}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8082:8082"
    networks:
      - psiboard-network
    depends_on:
      - discovery-service
      - rabbitmq
  
  notification-service:
    build: 
      context: ./notification-service
    image: notification-service
    container_name: notification-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - RABBITMQ_ADDRESS=${RABBITMQ_ADDRESS}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8083:8083"
    networks:
      - psiboard-network
    depends_on:
      - discovery-service
      - rabbitmq

  client-bff:
    build:
      context: ./client-bff
    image: client-bff
    container_name: client-bff
    environment:
      - NODE_ENV=production
      - API_GATEWAY_URL=http://gateway-service:8080
    ports:
      - 3000:3000
    networks:
      - psiboard-network

networks:
  psiboard-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: