version: '3.1'

services:

  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: psiboard-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest